/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/MovimentacaoEntrada`; params?: Router.UnknownInputParams; } | { pathname: `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `/Principal`; params?: Router.UnknownInputParams; } | { pathname: `/MovimentacaoSaida`; params?: Router.UnknownInputParams; } | { pathname: `/RelatorioFinanceiro`; params?: Router.UnknownInputParams; } | { pathname: `/Configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/MovimentacaoEntrada`; params?: Router.UnknownOutputParams; } | { pathname: `/Perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/Principal`; params?: Router.UnknownOutputParams; } | { pathname: `/MovimentacaoSaida`; params?: Router.UnknownOutputParams; } | { pathname: `/RelatorioFinanceiro`; params?: Router.UnknownOutputParams; } | { pathname: `/Configuracoes`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Cadastro${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/MovimentacaoEntrada${`?${string}` | `#${string}` | ''}` | `/Perfil${`?${string}` | `#${string}` | ''}` | `/Principal${`?${string}` | `#${string}` | ''}` | `/MovimentacaoSaida${`?${string}` | `#${string}` | ''}` | `/RelatorioFinanceiro${`?${string}` | `#${string}` | ''}` | `/Configuracoes${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/MovimentacaoEntrada`; params?: Router.UnknownInputParams; } | { pathname: `/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `/Principal`; params?: Router.UnknownInputParams; } | { pathname: `/MovimentacaoSaida`; params?: Router.UnknownInputParams; } | { pathname: `/RelatorioFinanceiro`; params?: Router.UnknownInputParams; } | { pathname: `/Configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
